CREATE TABLE IF NOT EXISTS products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    moysklad_id UUID,
    name TEXT NOT NULL,
    article TEXT NOT NULL UNIQUE,
    price NUMERIC,
    country TEXT,
    image_url TEXT,
    status TEXT DEFAULT 'новый',
    moderation_result TEXT,
    airtable_id TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
