-- Add missing columns to products table
ALTER TABLE products 
ADD COLUMN IF NOT EXISTS category_id TEXT,
ADD COLUMN IF NOT EXISTS buy_price NUMERIC,
ADD COLUMN IF NOT EXISTS weight NUMERIC,
ADD COLUMN IF NOT EXISTS volume NUMERIC,
ADD COLUMN IF NOT EXISTS image_url TEXT,
ADD COLUMN IF NOT EXISTS quantity_reserve NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS archived BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS modifications_count INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS owner TEXT,
ADD COLUMN IF NOT EXISTS disable_kaspi BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS disable_dumping BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS preorder_days INTEGER;

-- Add missing columns to stock table
ALTER TABLE stock
ADD COLUMN IF NOT EXISTS stock_days NUMERIC;

-- Add missing columns to turnover table
ALTER TABLE turnover
ADD COLUMN IF NOT EXISTS uom_name TEXT,
ADD COLUMN IF NOT EXISTS uom_href TEXT,
ADD COLUMN IF NOT EXISTS image_href TEXT,
ADD COLUMN IF NOT EXISTS image_title TEXT,
ADD COLUMN IF NOT EXISTS image_filename TEXT,
ADD COLUMN IF NOT EXISTS image_updated TEXT,
ADD COLUMN IF NOT EXISTS image_tiny_href TEXT,
ADD COLUMN IF NOT EXISTS image_miniature_href TEXT,
ADD COLUMN IF NOT EXISTS assortment_href TEXT,
ADD COLUMN IF NOT EXISTS assortment_type TEXT,
ADD COLUMN IF NOT EXISTS on_period_start_quantity NUMERIC,
ADD COLUMN IF NOT EXISTS on_period_start_sum NUMERIC,
ADD COLUMN IF NOT EXISTS income_quantity NUMERIC,
ADD COLUMN IF NOT EXISTS income_sum NUMERIC,
ADD COLUMN IF NOT EXISTS outcome_quantity NUMERIC,
ADD COLUMN IF NOT EXISTS outcome_sum NUMERIC,
ADD COLUMN IF NOT EXISTS on_period_end_quantity NUMERIC,
ADD COLUMN IF NOT EXISTS on_period_end_sum NUMERIC;

-- Add missing columns to profit_by_product table
ALTER TABLE profit_by_product
ADD COLUMN IF NOT EXISTS uom_name TEXT,
ADD COLUMN IF NOT EXISTS image_url TEXT,
ADD COLUMN IF NOT EXISTS sell_quantity NUMERIC,
ADD COLUMN IF NOT EXISTS sell_price NUMERIC,
ADD COLUMN IF NOT EXISTS sell_cost NUMERIC,
ADD COLUMN IF NOT EXISTS sell_sum NUMERIC,
ADD COLUMN IF NOT EXISTS sell_cost_sum NUMERIC,
ADD COLUMN IF NOT EXISTS return_quantity NUMERIC,
ADD COLUMN IF NOT EXISTS return_price NUMERIC,
ADD COLUMN IF NOT EXISTS return_cost NUMERIC,
ADD COLUMN IF NOT EXISTS return_sum NUMERIC,
ADD COLUMN IF NOT EXISTS return_cost_sum NUMERIC,
ADD COLUMN IF NOT EXISTS sales_margin NUMERIC;

-- Add missing columns to money_by_account table
ALTER TABLE money_by_account
ADD COLUMN IF NOT EXISTS organization_name TEXT,
ADD COLUMN IF NOT EXISTS organization_href TEXT,
ADD COLUMN IF NOT EXISTS account_href TEXT;

-- Add missing columns to customer_orders table
ALTER TABLE customer_orders
ADD COLUMN IF NOT EXISTS vat_sum NUMERIC,
ADD COLUMN IF NOT EXISTS state_id TEXT,
ADD COLUMN IF NOT EXISTS agent_id TEXT,
ADD COLUMN IF NOT EXISTS organization_id TEXT,
ADD COLUMN IF NOT EXISTS store_id TEXT,
ADD COLUMN IF NOT EXISTS owner_id TEXT,
ADD COLUMN IF NOT EXISTS group_id TEXT,
ADD COLUMN IF NOT EXISTS rate_currency TEXT,
ADD COLUMN IF NOT EXISTS rate_value NUMERIC,
ADD COLUMN IF NOT EXISTS rate_multiplier NUMERIC,
ADD COLUMN IF NOT EXISTS printed BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS published BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS deleted TIMESTAMP WITH TIME ZONE;

-- Add missing columns to payments_in table
ALTER TABLE payments_in
ADD COLUMN IF NOT EXISTS incoming_number TEXT,
ADD COLUMN IF NOT EXISTS incoming_date TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS vat_sum NUMERIC,
ADD COLUMN IF NOT EXISTS rate_currency TEXT,
ADD COLUMN IF NOT EXISTS rate_value NUMERIC,
ADD COLUMN IF NOT EXISTS rate_multiplier NUMERIC,
ADD COLUMN IF NOT EXISTS agent_id TEXT,
ADD COLUMN IF NOT EXISTS organization_id TEXT,
ADD COLUMN IF NOT EXISTS group_id TEXT,
ADD COLUMN IF NOT EXISTS owner_id TEXT,
ADD COLUMN IF NOT EXISTS state_name TEXT,
ADD COLUMN IF NOT EXISTS state_id TEXT,
ADD COLUMN IF NOT EXISTS operations TEXT;

-- Add missing columns to payments_out table
ALTER TABLE payments_out
ADD COLUMN IF NOT EXISTS incoming_number TEXT,
ADD COLUMN IF NOT EXISTS incoming_date TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS vat_sum NUMERIC,
ADD COLUMN IF NOT EXISTS rate_currency TEXT,
ADD COLUMN IF NOT EXISTS rate_value NUMERIC,
ADD COLUMN IF NOT EXISTS rate_multiplier NUMERIC,
ADD COLUMN IF NOT EXISTS agent_id TEXT,
ADD COLUMN IF NOT EXISTS organization_id TEXT,
ADD COLUMN IF NOT EXISTS group_id TEXT,
ADD COLUMN IF NOT EXISTS owner_id TEXT,
ADD COLUMN IF NOT EXISTS state_name TEXT,
ADD COLUMN IF NOT EXISTS state_id TEXT,
ADD COLUMN IF NOT EXISTS operations TEXT;

-- Add missing columns to cash_in table
ALTER TABLE cash_in
ADD COLUMN IF NOT EXISTS incoming_number TEXT,
ADD COLUMN IF NOT EXISTS incoming_date TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS organization_id TEXT,
ADD COLUMN IF NOT EXISTS agent_id TEXT,
ADD COLUMN IF NOT EXISTS state_name TEXT,
ADD COLUMN IF NOT EXISTS state_id TEXT,
ADD COLUMN IF NOT EXISTS rate_currency TEXT,
ADD COLUMN IF NOT EXISTS rate_value NUMERIC,
ADD COLUMN IF NOT EXISTS rate_multiplier NUMERIC,
ADD COLUMN IF NOT EXISTS group_id TEXT,
ADD COLUMN IF NOT EXISTS owner_id TEXT;

-- Add missing columns to cash_out table
ALTER TABLE cash_out
ADD COLUMN IF NOT EXISTS incoming_number TEXT,
ADD COLUMN IF NOT EXISTS incoming_date TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS organization_id TEXT,
ADD COLUMN IF NOT EXISTS agent_id TEXT,
ADD COLUMN IF NOT EXISTS state_name TEXT,
ADD COLUMN IF NOT EXISTS state_id TEXT,
ADD COLUMN IF NOT EXISTS rate_currency TEXT,
ADD COLUMN IF NOT EXISTS rate_value NUMERIC,
ADD COLUMN IF NOT EXISTS rate_multiplier NUMERIC,
ADD COLUMN IF NOT EXISTS group_id TEXT,
ADD COLUMN IF NOT EXISTS owner_id TEXT;

-- Add missing columns to losses table
ALTER TABLE losses
ADD COLUMN IF NOT EXISTS account_id TEXT,
ADD COLUMN IF NOT EXISTS owner TEXT,
ADD COLUMN IF NOT EXISTS shared BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS group_id TEXT,
ADD COLUMN IF NOT EXISTS updated TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS description TEXT,
ADD COLUMN IF NOT EXISTS external_code TEXT,
ADD COLUMN IF NOT EXISTS applicable BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS store TEXT,
ADD COLUMN IF NOT EXISTS organization TEXT,
ADD COLUMN IF NOT EXISTS created TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS printed BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS published BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS inventory TEXT,
ADD COLUMN IF NOT EXISTS project TEXT;
