
ALTER TABLE products ADD COLUMN IF NOT EXISTS category TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS category_id TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS external_code TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS weight NUMERIC;
ALTER TABLE products ADD COLUMN IF NOT EXISTS volume NUMERIC;
ALTER TABLE products ADD COLUMN IF NOT EXISTS image_url TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS quantity_reserve NUMERIC DEFAULT 0;
ALTER TABLE products ADD COLUMN IF NOT EXISTS modifications_count NUMERIC DEFAULT 0;
ALTER TABLE products ADD COLUMN IF NOT EXISTS owner TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS disable_kaspi BOOLEAN DEFAULT false;
ALTER TABLE products ADD COLUMN IF NOT EXISTS disable_dumping BOOLEAN DEFAULT false;
ALTER TABLE products ADD COLUMN IF NOT EXISTS preorder_days NUMERIC;
